#####################################################################
################### DO NOT EDIT THIS FILE ###########################
#####################################################################
# FROM selenium/standalone-chrome:114.0.5735.133-chromedriver-114.0.5735.90
FROM selenium/standalone-chrome:116.0.5845.140-chromedriver-116.0.5845.96

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-upgrade \
        python3 \
        python3-pip \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatspi2.0-0 \
        libcairo2 \
        libcups2 \
        libgbm1 \
        libgdk-pixbuf2.0-0 \
        libgtk-3-0 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libxcursor1 \
        libxss1 \
        xdg-utils \
        python3-tk \
        python3-dev \
        tesseract-ocr \
        xvfb \
	&& apt-get clean

# Set the working directory for any subsequent ADD, COPY, CMD, ENTRYPOINT,
# or RUN instructions that follow it in the Dockerfile
WORKDIR /what_contact

# Copy files or folders from source to the dest path in the image's filesystem.
COPY . ./

# Update awscli
# RUN sudo pip install awscli --ignore-installed six

# Setup Python environment
RUN sudo ln -s /usr/bin/python3 /usr/bin/python

# RUN sudo pip3 install Pillow
RUN sudo pip3 install -r requirements.txt

RUN sudo chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
# CMD ["/bin/bash"]
CMD python main.py